version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sunwise_db
    environment:
      POSTGRES_USER: url_master
      POSTGRES_PASSWORD: SomeReallyStrongPassword123
      POSTGRES_DB: sunwise_url_shortener
    ports:
      - "5433:5432"
    volumes:
      - ./Postgres/data:/var/lib/postgresql/data
      - ./Postgres/backups:/backups

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sunwise_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - ./Postgres/pgadmin:/var/lib/pgadmin
